variable "vpc_cidr" {}
variable "tag-vpc" {}
variable "keypair" {}
variable "public_keypair_path" {} 
variable "tag-keypair" {}
variable "AZ1" {}
variable "PSN1_cidr" {}
variable "tag-subnet-1" {}
variable "AZ2" {}
variable "PSN2_cidr" {}
variable "tag-subnet-2" {}
variable "PrSN1_cidr" {}
variable "tag-private-subnet-1" {}
variable "PrSN2_cidr" {}
variable "tag-private-subnet-2" {}
variable "tag-igw" {}
variable "tag-ngw" {}
variable "tag-public_rt" {}
variable "all_cidr" {}
variable "tag-private_rt" {}
variable "ssh_port" {}
variable "port_proxy" {}
variable "http_port" {}
variable "https_port" {}
variable "tag-docker-sg" {}
variable "tag-jenkins-sg" {}
variable "tag-bastion_ansible-sg" {}
variable "port_nexus" {} 
variable "port_nexus2" {}
variable "tag-nexus-sg" {}
variable "mysql_port" {}
variable "port_sonarqube" {}
variable "tag-sonarqube-sg" {}
variable "tag-mysql" {}