variable "ec2_ami" {}
variable "instance_type" {}
variable "security_group_ids" {}
variable "subnet_id" {}
variable "key_name" {}
variable "tag-ansible-server" {}
variable "stage-playbook" {}
variable "prod-playbook" {}
variable "stage-bash-script" {}
variable "prod-bash-script" {}
variable "stage-trigger" {}
variable "prod-trigger" {}
variable "password" {}
variable "private-key" {}
variable "nexus-server-ip" {}